---
- name: Install nginx for apt systems
  block:
    - name: Install requirenments
      apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
        update_cache: true

    - name: Add nginx repository key
      apt_key:
        id: 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
        url: https://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add nginx repository
      apt_repository:
        repo: "deb http://nginx.org/packages/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} nginx"
        state: present
        filename: "nginx"

    - name: Install nginx for apt
      apt:
        name:  "nginx={{ minirole__nginx_version }}*"
        update_cache: true
      notify:
        - enable_nginx

  when: ansible_os_family == "Debian"

- name: Install nginx for rpm systems
  block:
    - name: Add yum repository
      yum_repository:
        name: "nginx-{{ minirole__nginx_version }}"
        description: Nignx stable repo
        baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
        gpgcheck: true
        gpgkey: https://nginx.org/keys/nginx_signing.key

    - name: Install nginx for rpm
      yum:
        name: nginx
      notify:
        - enable_nginx

  when: ansible_os_family == "RedHat"

- name: Create vhost root directory
  file:
    state: directory
    path: "{{ minirole__vhost_root }}"
    owner: nginx
    group: nginx
    mode: 0760

- name: Setup main vhost
  template:
    src: default.conf.j2
    owner: nginx
    group: nginx
    mode: 0660
    dest: /etc/nginx/conf.d/default.conf
  notify:
    - restart_nginx

- name: Deploy app =)
  template:
    src: index.html.j2
    dest: "{{ minirole__vhost_root }}/index.html"
    owner: nginx
    group: nginx
    mode: 0760
