# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y dbus systemd openssh-server python sudo bash ca-certificates iproute2 python-apt aptitude && apt-get clean && mkdir -p /var/run/sshd; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y /usr/bin/python /usr/bin/python2-config sudo yum-plugin-ovl bash iproute openssh-server systemd && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; fi && \
    ssh-keygen -A -f . && \
    find /lib/systemd/system/sysinit.target.wants/ -type l -and -not -name systemd-tmpfiles-setup.service -delete && \
    find /etc/systemd/system/*.wants -type l -not -name ntpd.service -and -not -iname "ssh*" -delete


RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y init; fi

VOLUME ["/sys/fs/cgroup"]
CMD ["/sbin/init"]
